config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings
import system.views as sys_func


handler403 = sys_func.tr_handler403
handler404 = sys_func.tr_handler404
handler500 = sys_func.tr_handler500

urlpatterns = [
    path("", sys_func.MainPage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path('captcha/', include('captcha.urls')),
    path("to-do/", include("todo_app.urls")),
    path("post/", include("blog.urls")),
    path("run/", include("run.urls")),
    path("read/", include(("read.urls", 'read'), namespace='read_app')),
    path('feedback/', sys_func.contact_view, name='feedback'),
    path('success/', sys_func.success_view, name='success'),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns

read/urls.py
from django.urls import path
from read import views as vs
from django.views.decorators.cache import cache_page

urlpatterns = [
     path("",
          cache_page(30)(vs.HomeListView.as_view()), name="read_home"),
     # year
     path("<int:year_id>/", vs.YearListView.as_view(), name="read_year"),
     path("new_year/", vs.YearCreateView.as_view(), name="year_new"),
     path("year_list/", vs.YearEditListView.as_view(), name="year_list"),
     path("delete/<int:pk>/", vs.YearDeleteView.as_view(), name='del_year'),
     path("update/<int:pk>/", vs.YearEditView.as_view(), name='edit_year'),
     # book
     path("new_book/", vs.BookCreateView.as_view(), name="book_new"),
     path("del_book/<int:pk>/", vs.BookDeleteView.as_view(), name='del_book'),
     path("upd_book/<int:pk>/", vs.BookUpdView.as_view(), name='update_book'),
]

run/urls.py
from django.urls import path
from run import views as vs

urlpatterns = [
    path("", vs.RunListView.as_view(), name="run_home"),
    path("new_year/", vs.RunYearCreateView.as_view(), name="new_year"),
    path("year_list/", vs.RunYearListView.as_view(), name="year_list"),
    path("<int:pk>/delete_year/", vs.RunDelView.as_view(), name="delete_year"),
    path("<int:pk>/edit_year/", vs.RunUpdateView.as_view(), name="edit_year"),
]

read/models.py
from django.db import models
from django.urls import reverse


class Year(models.Model):
    title = models.PositiveIntegerField(unique=True, verbose_name='Год')

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse('read_app:read_home')


class Book(models.Model):
    LANG = (
        ('rus', 'Русский'),
        ('eng', 'Английский'),
    )

    title = models.CharField(unique=True,
                             verbose_name='Название', max_length=140)

    author = models.CharField(max_length=140, verbose_name='Автор')

    year = models.ForeignKey(Year, related_name='books',
                             on_delete=models.CASCADE,
                             verbose_name='Год прочтения')

    language = models.CharField(max_length=3, choices=LANG,
                                verbose_name='Язык')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('read_app:read_home')

read/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy

from read.models import Book, Year


class HomeListView(ListView):
    model = Year
    template_name = "read/read_home.html"
    context_object_name = 'years'


class YearListView(ListView):
    model = Book
    template_name = "read/read_year.html"
    context_object_name = 'books'

    def get_queryset(self):
        books_by_year = Book.objects.filter(year_id=self.kwargs["year_id"])
        return books_by_year.select_related('year')

    def get_context_data(self):
        context = super().get_context_data()
        context["year"] = Year.objects.get(id=self.kwargs["year_id"])
        return context


class YearCreateView(UserPassesTestMixin, CreateView):
    model = Year
    fields = ('title',)
    template_name = "read/read_create.html"

    def test_func(self):
        return self.request.user.is_staff


class BookCreateView(UserPassesTestMixin, CreateView):
    model = Book
    fields = '__all__'
    template_name = "read/book_create.html"

    def test_func(self):
        return self.request.user.is_staff


class BookDeleteView(UserPassesTestMixin, DeleteView):
    model = Book
    fields = '__all__'
    template_name = 'read/delete_book.html'
    success_url = reverse_lazy('read_app:year_list')

    def test_func(self):
        return self.request.user.is_staff


class BookUpdView(UserPassesTestMixin, UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'read/upd_book.html'
    success_url = reverse_lazy('read_app:year_list')
    context_object_name = 'book'

    def test_func(self):
        return self.request.user.is_staff


class YearEditListView(ListView):
    model = Year
    fields = '__all__'
    template_name = 'read/year_list.html'
    context_object_name = 'years'


class YearDeleteView(UserPassesTestMixin, DeleteView):
    model = Year
    fields = '__all__'
    template_name = 'read/delete_year.html'
    success_url = reverse_lazy('read_app:read_home')

    def test_func(self):
        return self.request.user.is_staff


class YearEditView(UserPassesTestMixin, ListView):
    model = Book
    fields = '__all__'
    template_name = 'read/edit_year.html'
    success_url = reverse_lazy('read_app:read_home')

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self):
        context = super().get_context_data()
        context['year'] = Year.objects.get(id=self.kwargs['pk'])
        context["books"] = Book.objects.filter(year_id=self.kwargs["pk"])
        return context

templates/read/book_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Новая книга {% endblock title %}

{% block content %}
<h3 class="h3"> Добавь книгу </h3>
<form action="" method="post"> {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-secondary" > Добавить </button>
</form>
<hr>
<br>
{% endblock content %}

templates/read/delete_book.html
{% extends 'base.html' %}

{% block title %} Удалить книгу {% endblock title %}

{% block content %}
<br>
<form action="" method="post"> {% csrf_token %}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Удалить книгу</h4>
        <p>Ты уверен, что хочешь удалить {{ object.title }} книгу?</p>
        <button type="submit" class="btn btn-danger" >Удалить</button>
      </div>
</form>
<br>
<hr>
{% endblock content %}

templates/read/delete_year.html
{% extends 'base.html' %}

{% block title %} Удалить год {% endblock title %}

{% block content %}
<br>
<form action="" method="post"> {% csrf_token %}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Удалить год</h4>
        <p>Ты уверен, что хочешь удалить {{ object.year }} год?</p>
        <button type="submit" class="btn btn-danger" >Удалить</button>
      </div>
</form>
<br>
<hr>
{% endblock content %}

templates/read/edit_year.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Редактирование {{ year }} {% endblock title %}

{% block content %}

<br>
<div class="alert alert-secondary" role="alert">
        <h4 class="alert-heading">Редактировать или удалить книгу</h4>
        <p class="mb-0">Список:</p>
        <hr>
        {% for book in books %}
        <p> Название: {{ book.title }}</p>
        <button type="button" class="btn btn-outline-danger"
        onclick="location.href='{% url "read_app:del_book" book.pk %}'"/>
        Удалить
        </button>
       <button type="button" class="btn btn-outline-secondary"
                onclick="location.href='{% url "read_app:update_book" book.pk %}'"/>
        Редактировать
        </button>
        <hr>
        {% endfor %}
<hr>
<br>
{% endblock content %}

templates/read/read_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Новый год  {% endblock title %}

{% block content %}
<h3 class="h3"> Новый год </h3>
<form action="" method="post"> {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-secondary" >Добавить</button>
</form>
<hr>
<br>
{% endblock content %}

templates/read/read_home.html
{% extends 'base.html' %}
{% load read_tags %}
{% load static %}
{% block title %} Библиотека {% endblock title %}

{% block content %}
<h2 align="center"><font color="1B545F" face="Ubuntu"> Книжная полка по годам </font> </h2>
<!--<img class="run" src="{% static 'images/buty1.jpg' %}">-->
<p></p>
<table border="1" class="table table-striped" style="width:80%; margin-left: auto; margin-right: auto;
    text-align:center;">
  <thead>
  <tr>
    <th>Год</th>
    <th>Общее количество</th>
    <th> На русском </th>
    <th> На английском </th>
  </tr>
  </thead>
  <tbody>
  {% for year in years %}
  <tr>
      <th> <a href="{% url 'read_app:read_year' year.id %}">{{ year.title }} </a> </th>
      {% count_by_lang year as count_dict %}
      <td class="table-primary">{{ count_dict.total }}</td>
      <td>{{ count_dict.rus }}</td>
      <td>{{ count_dict.eng }}</td>
  </tr>
  {% endfor %}
  <tbody>
</table>
<div style="width:55%; margin-left: auto; margin-right: auto;">
<button type="button" class="btn btn-outline-secondary"
        onclick="location.href='{% url "read_app:year_new" %}'"/>
        Добавить год
</button>
<button type="button" class="btn btn-outline-secondary"
        onclick="location.href='{% url "read_app:year_list" %}'"/>
        Редактировать год
</button>
<button type="button" class="btn btn-outline-secondary"
        onclick="location.href='{% url "read_app:book_new" %}'"/>
Добавить книгу
</button>
</div>

{% endblock content %}

templates/read/read_year.html
{% extends "base.html" %}
{% block title %} {{ year }} {% endblock %}
{% load static %}
{% block content %}
<img class="book" src="{% static 'images/books.png' %}">
<br>
<h3 class="h3">{{ year }}</h3>
<br>
<div class="l_books">
<ul>
    {% for book in books %}
    <li>{{ book.title }} от автора: {{ book.author }} ({{ book.language }})</li>
    {% endfor %}
</ul>
</div>
{% endblock %}

templates/read/upd_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Редактирование {{ book.title }} {% endblock title %}

{% block content %}
<h3> Редактирование {{ book.title }} </h3>
<br>
<div class="alert alert-secondary" role="alert">
        <h4 class="alert-heading">Редактировать или удалить книгу</h4>
        <p class="mb-0">Список:</p>
        <hr>
    <form method="post">
        {% csrf_token %}
    {{ form|crispy}}
    <button type="submit" class="btn btn-outline-secondary" >Сохранить</button>
    </form>
<hr>
<br>
{% endblock content %}

templates/read/year_list.html
{% extends 'base.html' %}

{% block title %} Редактировать {% endblock title %}

{% block content %}
<br>
<div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Редактировать или удалить год</h4>
        <p class="mb-0">Список:</p>
        <hr>
        {% for year in years %}
        <p>{{ year.title }} год </p>
        <button type="button" class="btn btn-outline-danger"
        onclick="location.href='{% url "read_app:del_year" year.pk %}'"/>
        Удалить
        </button>
        <button type="button" class="btn btn-outline-danger"
                onclick="location.href='{% url "read_app:edit_year" year.pk %}'"/>
        Редактировать
        </button>
        <hr>
        {% endfor %}
        </div>
{% endblock content %}