config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings
import system.views as sys_func


handler403 = sys_func.tr_handler403
handler404 = sys_func.tr_handler404
handler500 = sys_func.tr_handler500

urlpatterns = [
    path("", sys_func.MainPage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path('captcha/', include('captcha.urls')),
    path("to-do/", include("todo_app.urls")),
    path("post/", include("blog.urls")),
    path("run/", include("run.urls")),
    path("read/", include(("read.urls", 'read'), namespace='read_app')),
    path('feedback/', sys_func.contact_view, name='feedback'),
    path('success/', sys_func.success_view, name='success'),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns

read/urls.py
from django.urls import path
from read import views as vs
from django.views.decorators.cache import cache_page

urlpatterns = [
     path("",
          cache_page(30)(vs.HomeListView.as_view()), name="read_home"),
     # year
     path("<int:year_id>/", vs.YearListView.as_view(), name="read_year"),
     path("new_year/", vs.YearCreateView.as_view(), name="year_new"),
     path("year_list/", vs.YearEditListView.as_view(), name="year_list"),
     path("delete/<int:pk>/", vs.YearDeleteView.as_view(), name='del_year'),
     path("update/<int:pk>/", vs.YearEditView.as_view(), name='edit_year'),
     # book
     path("new_book/", vs.BookCreateView.as_view(), name="book_new"),
     path("del_book/<int:pk>/", vs.BookDeleteView.as_view(), name='del_book'),
     path("upd_book/<int:pk>/", vs.BookUpdView.as_view(), name='update_book'),
]

run/urls.py
from django.urls import path
from run import views as vs

urlpatterns = [
    path("", vs.RunListView.as_view(), name="run_home"),
    path("new_year/", vs.RunYearCreateView.as_view(), name="new_year"),
    path("year_list/", vs.RunYearListView.as_view(), name="year_list"),
    path("<int:pk>/delete_year/", vs.RunDelView.as_view(), name="delete_year"),
    path("<int:pk>/edit_year/", vs.RunUpdateView.as_view(), name="edit_year"),
]

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}Deriabin Home App{% endblock title %}</title>
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">
     <img src="{% static 'images/logo1.jpg' %}">
  </a>
  <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog_home' %}"> Блог </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">Дела</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'run_home' %}">Бег</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'read_app:read_home' %}">Чтение</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'feedback' %}">Feedback</a>
      </li>
  </ul>

  {% if user.is_authenticated %}

  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
    <li class="nav-item">
    <a class="nav-link dropdown-toggle" href="#"
      id="navbarDropdown" role="button" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false">
    {{ user.username }}
  </a>
  <div class="dropdown-menu dropdown-menu-lg-right"
    aria-labelledby="navbarDropdown">
  <a class="dropdown-item"
    href="{% url 'password_change' %}">Change password</a>
  <div class="dropdown-divider"></div>
<a class="dropdown-item" href="{% url 'logout' %}"> Log Out </a>
   </div>
   </li>
   </ul>
{% else %}
<form class="form-inline ml-auto">
<a href="{% url 'login' %}" class="btn btn-outline-secondary">
Log In</a>
<a href="{% url 'signup' %}" class="btn btn-primary ml-2">
Sign up</a>
</form>
{% endif %}
</div>
</nav>

<main>
<div class="container">
{% block content %}
{% endblock content %}
</div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>


</body>
</html>